All libraries needed for this notebook outside of jupyter itself, run this cell to make sure you have the proper libraries.

In [1]:
import numpy as np

Initialize two Python list objects below.
Remember that [] initiates a list object the same as calling list().
This is also true for other data structures in Python such as dictionaries (hash map / hash table) {} or dict().

In [4]:
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]
print(a)
print(b)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]


What does a + b create?

In [5]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Notice that the two lists did not sum the internal elements of each list, but rather contantenated the two list objects in a single list, while maintaining the order of the internal elements. Lists are ordered objects, Dictionaries are not.

In [6]:
sum_result = []
for first, second in zip(a,b):
    sum_temp = first + second
    sum_result.append(sum_temp)
print(sum_result)

[7, 9, 11, 13, 15]


While this works for a small amount of numbers in a single dimensional list, it will become increasingly slow as each new dimension requires an additional for loop. Each new nested for loop increases the time complexity from n -> n^2 -> n^3. As you will soon see image data is often represented as 2, 3 or 4 dimensional arrays.
Arrays are not Lists, though they often first appear similiar in Python.

We can instantiate numpy arrays by providing a list.

In [7]:
c = np.array(a)
d = np.array(b)
print(type(a), type(b))
print(type(c), type(d))

<class 'list'> <class 'list'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [8]:
c + d

array([ 7,  9, 11, 13, 15])

Notice how we did not need to create a for loop in order to add the internal elements of the two arrays c and d together. Instead numpy automatically vectorized the sum operation. It is also possible to do this with a vector (array) and a scalar (a single value or constant).

In [9]:
c + 2

array([3, 4, 5, 6, 7])

However, both lists and numpy arrays share a common index slicing syntax, which can cause confusion early in your Python career. Notice that objects of class ndarray do not have commas between the elements, while Python list objects do.

In [11]:
print('Type of a: {}'.format(type(a)))
print('Complete value of a: {}'.format(a))
print('First element of a: {}'.format(a[0]))
print('First two elements of a: {}'.format(a[0:2]))
print('Last element of a: {}'.format(a[-1]))
print('Object a reversed order: {}'.format(a[::-1]))
print('Type of c: {}'.format(type(c)))
print('Complete value of c: {}'.format(c))
print('First element of c: {}'.format(c[0]))
print('First two elements of c: {}'.format(c[0:2]))
print('Last element of c: {}'.format(c[-1]))
print('Object c reversed order: {}'.format(c[::-1]))

Type of a: <class 'list'>
Complete value of a: [1, 2, 3, 4, 5]
First element of a: 1
First two elements of a: [1, 2]
Last element of a: 5
Object a reversed order: [5, 4, 3, 2, 1]
Type of c: <class 'numpy.ndarray'>
Complete value of c: [1 2 3 4 5]
First element of c: 1
First two elements of c: [1 2]
Last element of c: 5
Object c reversed order: [5 4 3 2 1]


One of the reasons index slicing is so powerful is for value reassignment or selection. Notice that Python is 0-indexed, hence a 5-element list or array has indices 0-4 not 1-5.

In [12]:
a[0] = 10
c[4] = 10
print(a)
print(c)

[10, 2, 3, 4, 5]
[ 1  2  3  4 10]


In [13]:
print(len(a))
print(c.shape)
print(c.ndim)

5
(5,)
1


Notice that the shape of an array returns an immutable tuple where each element is a dimension and the integer value of the number of elements in that dimension (i.e. len() of c.shape is c.ndim or the # of dimensions). But how do you create a 2 dimensional array, (i.e. a matrix)?

In [14]:
# e is created from a list of lists
e = np.array([a, c])
print(type(e))
print(e.shape)
print(e.ndim)
print(e)

<class 'numpy.ndarray'>
(2, 5)
2
[[10  2  3  4  5]
 [ 1  2  3  4 10]]


Exercise: Create a 3 dimensional array and print the type, shape, n-dimensions, and size. How are shape and size related?

In [12]:
# Cell for Exercise



Solution:

In [15]:
f = np.array([e,e])
print(type(f))
print(f.shape)
print(f.ndim)
print(f)

<class 'numpy.ndarray'>
(2, 2, 5)
3
[[[10  2  3  4  5]
  [ 1  2  3  4 10]]

 [[10  2  3  4  5]
  [ 1  2  3  4 10]]]
